apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        kubernetes.io/arch: arm64  # Ensure pods are scheduled on ARM64 nodes
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: 500m  # Request 0.5 CPU (adjust based on the node's capacity)
              memory: 512Mi  # Request 512Mi of memory (adjust as needed)
            limits:
              cpu: 1
              memory: 1Gi  # Set appropriate memory limit
